apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: cloudflare-tunnel
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: cloudflare-tunnel.io/ingress
